#!/bin/bash

case $1 in
    start)
        echo ========== hadoop102上启动hdfs ==========
        ssh hadoop102 "source /etc/profile ; start-dfs.sh"

        echo ========== hadoop103上启动yarn ==========
        ssh hadoop103 "source /etc/profile ; start-yarn.sh"

        echo ========== hadoop102上启动历史服务器 ==========
        ssh hadoop102 "source /etc/profile ; mr-jobhistory-daemon.sh start historyserver"
   ;;
   stop)
        echo ========== hadoop102上停止hdfs ==========
        ssh hadoop102 "source /etc/profile ; stop-dfs.sh"

        echo ========== hadoop103上停止yarn ==========
        ssh hadoop103 "source /etc/profile ; stop-yarn.sh"

        echo ========== hadoop102上停止历史服务器 ==========
        ssh hadoop102 "source /etc/profile ; mr-jobhistory-daemon.sh stop historyserver"
   ;;
   *)
   echo "========== 启动姿势不正确 =========="
   echo "===start 启动hadoop集群"
   echo "===stop  停止hadoop集群"
   ;;

esac
